name = "weather-agency-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "weather-agency-db"
database_id = "361cbb4c-7b49-4e97-ba9a-27d9aa7e53cf"

[vars]
CORS_ORIGIN = "https://weather.agency"
FRONTEND_URL = "https://weather.agency"

[[send_email]]
name = "SEND_EMAIL"
